### ISSUE TITLE
AnnotationInspector bean ordering issues

### ISSUE THREAD

**Issue by kmudrick** [kdgregory/pathfinder#3]
If you define a bean that extends another bean, and that parent bean has not been imported before the child bean was, the AnnotationInspector ends up passing null to the AnnotationParser constructor (which throws a NPE)

Reordering the bean definition imports fixes the problem, but that solution is not immediately obvious (and spring itself handles it just fine...)

**Comment by kdgregory** [comment]
To clarify: is this happening with a classpath scan (and inheritance defined by Java) or XML beans (with inheritance defined in the config file)? Or separate classpath scans from config files?

**Comment by kmudrick** [comment]
Xml Config

-kevin

On Mar 10, 2013, at 9:08 AM, Keith Gregory notifications@github.com wrote:

To clarify: is this happening with a classpath scan (and inheritance
defined by Java) or XML beans (with inheritance defined in the config file)?

—
Reply to this email directly or view it on
GitHubhttps://github.com/kdgregory/pathfinder/issues/3#issuecomment-14681068
.

**Comment by kdgregory** [comment]
OK, last question (I'm looking to construct a testcase): does this bean inherit its class from its parent? ((that would seem to be the only way this problem could happen).

**Comment by kmudrick** [comment]
Yes

**Comment by kdgregory** [comment]
Now support inheritance of class and properties in XML bean definitions (147e88be1c37be300dfde9b920dadb23bad08990).
